/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Frame;
import java.sql.*;
import javax.swing.JOptionPane;
//import Project.ConnectionProvider;
/**
 *
 * @author USER
 */
public class Return_Book extends javax.swing.JFrame {

    /**
     * Creates new form Return_Book
     */
    public Return_Book() {
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        uid = new javax.swing.JTextField();
        idate = new javax.swing.JTextField();
        ddate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOK ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 84, 218, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 182, 218, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISSUE DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 273, 218, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DUE DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 358, 218, 38);
        getContentPane().add(bid);
        bid.setBounds(621, 84, 300, 50);
        getContentPane().add(uid);
        uid.setBounds(621, 182, 300, 50);
        getContentPane().add(idate);
        idate.setBounds(621, 273, 300, 50);
        getContentPane().add(ddate);
        ddate.setBounds(621, 367, 300, 38);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Icon 1\\Icon 1\\search.png")); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1014, 182, 210, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Icon 1\\Icon 1\\return book png.png")); // NOI18N
        jButton2.setText("RETURN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(346, 493, 200, 55);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Icon 1\\Icon 1\\red-x-mark-transparent-background-3.png")); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 490, 200, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Desktop\\25.chair-with-books-background-bookshelves-library-background_105428-3837.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-90, 0, 3140, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {  
    setVisible(false);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String bookid=bid.getText();
       String userid=uid.getText();
       try
       {
           Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "Sriram@123");
  Statement stm=conn.createStatement();
  ResultSet rs=stm.executeQuery("select * from issue where book_id='"+bookid+"'and user_id='"+userid+"'");
  if(rs.next())
  {
      idate.setText(rs.getString(3));
      ddate.setText(rs.getString(4));
      bid.setEditable(false);
      uid.setEditable(false);
  }
  else
  {
      JOptionPane.showMessageDialog(null,"Book is not issued to this user");
      setVisible(false);
      new Return_Book().setVisible(true);
  }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,"Connection Error");
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String bookid=bid.getText();
String userid=uid.getText();
try
{
   Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "Sriram@123");
  Statement stm=conn.createStatement();
 stm.executeUpdate("update issue set return_book='YES' where user_id='"+userid+"' and book_id='"+bookid+"'");
 stm.executeUpdate("update books set copies=copies+1");
 JOptionPane.showMessageDialog(null,"Book Successfully returned");
 setVisible(false);
 new Return_Book().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
/*
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
*/
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Connection Error");
}
    }
    //private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
      //  setVisible(false);
    //}   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField ddate;
    private javax.swing.JTextField idate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
